stages:
  - build
#  - test
  - deploy

image: ruby:2.6

cache:
  paths:
  - vendor/

build_env:
  stage: build
  before_script:
    - gem install bundler
    - bundle install
  script:
    - bundle exec jekyll build
  artifacts:
    paths:
      - _site
  only:
    - master

# Dimatikan agar lebih cepat
#testing:
#  image: vishnu667/htmlproofer
#  stage: test
#  script:
#    - htmlproofer ./_site --disable-external
      #- docker run -v $PWD/_site:/site mtlynch/htmlproofer /site
#  dependencies:
#    - build_env
#  only:
#    - master
#  allow_failure: true
#  tags:
#    - alpine

start_deploy:
  stage: deploy
  image: alpine:3.11
  cache: {}
  before_script:
    - apk add --no-cache openssh-client ca-certificates bash rsync
    - eval $(ssh-agent -s)
    - /bin/bash -c 'ssh-add <(echo "$PRIVKEY")'
  script:
    - scp -r -o StrictHostKeyChecking=no _site $DEPLOY_USER@$DEPLOY_HOST:/var/www/workspace
  dependencies:
    - build_env
  only:
    - master

